_wandb:
    value:
        cli_version: 0.21.0
        e:
            pb7epbjo39gpcf3wqjwflv0neqnsilog:
                codePath: main_pytorch.py
                codePathLocal: main_pytorch.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "395184570368"
                        used: "37736488960"
                email: panhalay69420@gmail.com
                executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
                git:
                    commit: 74000792dec3484cb8d28cd76817d132e8b7092f
                    remote: https://github.com/LaySopanha/GE_WAR.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-f0f872a9-3960-c21c-15c4-7e0c27a95931
                host: cs-01k06rfhw175p4e8fqv7n5yt5f
                memory:
                    total: "33652191232"
                os: Linux-6.8.0-1032-gcp-x86_64-with-glibc2.31
                program: /teamspace/studios/this_studio/ches2025_pytorch/main_pytorch.py
                python: CPython 3.10.10
                root: /teamspace/studios/this_studio/ches2025_pytorch
                startedAt: "2025-07-15T10:08:59.974451Z"
                writerId: pb7epbjo39gpcf3wqjwflv0neqnsilog
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 3
                - 13
                - 16
                - 62
            "4": 3.10.10
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
activation:
    value: selu
batch_size:
    value: 256
conv_layers:
    value: 2
dataset:
    value: CHES_2025
epochs:
    value: 50
filters:
    value: 16
kernel_initializer:
    value: glorot_uniform
kernels:
    value: 12
layers:
    value: 2
leakage:
    value: ID
lr:
    value: 0.001
max_shift:
    value: 15
model_type:
    value: cnn
name:
    value: Phase2_Test_Candidate_A
neurons:
    value: 256
noise_level:
    value: 0.05
optimizer:
    value: Adam
padding:
    value: 0
poi_end:
    value: 4519
poi_start:
    value: 4119
pooling_sizes:
    value: 2
pooling_types:
    value: average_pool
