_wandb:
    value:
        cli_version: 0.21.0
        e:
            o430et4z8tqus57atvrzme0c8la5c6ml:
                codePath: main_pytorch.py
                codePathLocal: main_pytorch.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "395184570368"
                        used: "32648482816"
                email: panhalay69420@gmail.com
                executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
                git:
                    commit: 88ca20c30460e682cab4b1b938dcbecfcb12e43f
                    remote: https://github.com/LaySopanha/GE_WAR.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-c56b3429-f353-7556-a8c9-6de7ecd5f4c3
                host: cs-01k06519wgc8tb18bxa5npx2m1
                memory:
                    total: "33652191232"
                os: Linux-6.8.0-1032-gcp-x86_64-with-glibc2.31
                program: /teamspace/studios/this_studio/ches2025_pytorch/main_pytorch.py
                python: CPython 3.10.10
                root: /teamspace/studios/this_studio/ches2025_pytorch
                startedAt: "2025-07-15T06:11:09.384100Z"
                writerId: o430et4z8tqus57atvrzme0c8la5c6ml
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 13
                - 16
            "4": 3.10.10
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
activation:
    value: selu
batch_size:
    value: 256
conv_layers:
    value: 3
dataset:
    value: CHES_2025
epochs:
    value: 50
filters:
    value: 8
kernel_initializer:
    value: glorot_uniform
kernels:
    value: 24
layers:
    value: 2
leakage:
    value: ID
lr:
    value: 0.001
max_shift:
    value: 15
model_type:
    value: cnn
name:
    value: Phase2_MLOps_CNN_Test
neurons:
    value: 256
noise_level:
    value: 0.05
optimizer:
    value: Adam
padding:
    value: 0
poi_end:
    value: 4519
poi_start:
    value: 4119
pooling_sizes:
    value: 2
pooling_types:
    value: average_pool
